### ISSUE TITLE
fastserve cannot be run concurrently even with different arguments

### ISSUE THREAD

**Issue by davepacheco** [joyent/node-fast#16]
While trying to induce the memory issues described under MORAY-455, I wanted to run a bunch of `fastserve` instances in the same zone to distribute load from many clients.  Unfortunately, you can't run `fastserve` more than once on the same system because they collide on their monitoring port.  We should probably provide a command-line argument for specifying the monitoring port so that you can do this.  We could even provide a default value based on the listen port plus some fixed offset, which ought to work in most cases.

(CC @KodyKantor)

**Comment by KodyKantor** [comment]
The suggested change uses default values for both the fast and monitoring TCP ports if none are provided. That means it won't exit with an error if there are no ports provided, which is different than the current implementation. It also moves away from positional arguments.

Testing notes:
* `make check` clean
* Tested the following error cases:
  * fast and monitor TCP ports are identical
  * fast port is at the end of the valid TCP port range, pushing the default monitoring port over the edge
  * fast port is a string (e.g. 'cat')
  * monitoring port is a string
* Tested running `fastserve` with no arguments, just the `--port` argument, and just the `--mon-port` argument
* Tested both the long and short form of each argument (e.g. `--port` and `-p`)
