### ISSUE TITLE
allow specifying ports used for fastbench CLI

### ISSUE THREAD

**Issue by jordanhendricks** [joyent/node-fast#20]
The port used for artedi metrics and the port used for kang are [hard-coded](https://github.com/joyent/node-fast/blob/master/bin/fastbench#L97-L98) in fastbench. In some cases, it is convenient to pass specific ports for these to use instead.

**Comment by jordanhendricks** [comment]
CR: https://cr.joyent.us/#/c/4537/.

**Automated Testing**:
- `make test` clean
- `make test-compat` clean

**Manual Testing**
_Invalid input_
The following invocations cause fastbench to exit non-zero and print the help message:
```
$ bin/fastbench -p foo sync localhost 2020
$ bin/fastbench -p -1 sync localhost 2020
$ bin/fastbench -p foo sync localhost 2020
$ bin/fastbench -k -1 sync localhost 2020 
```

_Valid input_
The following invocations start fastbench with the port specified by the user: fastbench started successfully, and I was able to hit the artedi endpoint in relevant cases with curl. (I tried to hit the kang endpoint when relevant with curl, and had trouble getting that working, but I suspect I'm using it incorrectly.)
```
# Both ports specified
 $ bin/fastbench -p 8000 -k 8001 sync localhost 2020

# Neither port specified
 $ bin/fastbench -p 8000 -k 8001 sync localhost 2020

# Only kang port specified
 $ bin/fastbench -k 8001 sync localhost 2020

# Only artedi port specified
 $ bin/fastbench -p 8000 sync localhost 2020
```

**Comment by davepacheco** [comment]
Just to be sure, did you also test not specifying either "-p" or "-k"?

**Comment by jordanhendricks** [comment]
Yes, I messed that up in the testing notes on that case, but I did test that. (Fixed.)

**Comment by jordanhendricks** [comment]
PS2 has updated long names for the flags. Here is the help message fastbench has now:
```
[root@91a5ff1c-9123-418c-b6a7-deb0d1cdeeac ~/jhendricks/node-fast]# bin/fastbench help
fastbench: expected workload, host, and port
usage: fastbench [OPTIONS] WORKLOAD HOST PORT
Runs Fast RPC requests to measure latency and throughput.

Available canned workloads:

    sync      uniform, moderate-sized, synchronous requests
    sleep150  uniform, moderate-sized requests with 150ms sleep

Options:

    -c | --concurrency N         Allow up to N outstanding requests at once
                                 (default: 1)
    -d | --duration NSECONDS     Stop after NSECONDS seconds.
    -i | --interval NSECONDS     Report every NSECONDS seconds.
    -n | --nrequests NREQUESTS   Stop after completing NREQUESTS requests.
    -p | --artedi-port PORT       Use PORT for metrics endpoint.
    -k | --kang-port PORT         Use PORT for kang endpoint.
```

I tested that using the long form for both ports works correctly and ran `make test` successfully.
