### ISSUE TITLE
Add accessor function for request start time

### ISSUE THREAD

**Issue by KodyKantor** [joyent/node-fast#8]
The `fsr_tstarted` field is useful for tracking the latency of individual requests. Kang currently exports this information but developers may also want to track latency to plug into a higher-level metric collection facility among other things.

We could add an accessor function for the `fsr_tstarted` field, similar to the way it is already being done for other private fields [here](https://github.com/joyent/node-fast/blob/002cc1100ea62f99a4366c9304b9ee76829026b1/lib/fast_server.js#L1068-L1109) to allow applications to track request latency.

**Comment by davepacheco** [comment]
Is the intent to put this into something like node-artedi?  Would it make sense to have something that consumers could pass into node-fast (similar to the way they can pass bunyan loggers) that would cause fast to attach counters and other metrics?  I think that might be a useful pattern.

My only concern with exposing the specific field is that there are likely lots of metrics we may want to expose in a similar way, some of which are probably implementation details, and it would be unfortunate if we had to add interfaces for all them.  We'd also have to add code in multiple places to add new metrics.

**Comment by KodyKantor** [comment]
Sure! That's a better idea. I'll close this and open a different ticket. Sorry, I should have seen this.
